# image directory
directory: /home/benjamin/Research/code/montager/culler_selected_imgs

# procesing notes
excell: /home/benjamin/Research/code/montager/masterCopy.xlsx

# where the photoshop scipt is saved
# to be used in photoshop it must be saved into the
# presets/scripts folder which is a part of photoshop
#photoshopDirectory: C:\Users\benda\Desktop\montager
photoshopDirectory: /home/benjamin/Research/code/montager

# which eye, for nominal position
eye: OD

# this is what will be replaced, for examples in some file names
# you have:
# blah_confocal_blahblahblah.tif
# blahblah_split_blahblah.tif
# blahblah_avg_blahblah.tif
naming:
  confocal: confocal
  split: split_det
  avg: avg


